#!/bin/bash
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/cendrawasih/database/ssh/ssh.db")
if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    echo -e "\e[42m            Delete SSH/OVPN Account        \E[0m"
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    echo ""
    echo "You have no existing clients!"
    echo ""
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
fi
clear
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
echo -e "\e[42m            Delete SSH/OVPN Account        \E[0m"
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
grep -E "### " "/etc/cendrawasih/database/ssh/ssh.db" | cut -d ' ' -f 2-3 | nl -s ') '
until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
    if [[ ${CLIENT_NUMBER} == '1' ]]; then
        read -rp "Select one client [1]: " CLIENT_NUMBER
    else
        read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
    fi
done

echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\e[42m                 DELETE USER             \E[0m"
echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
user=$(grep -E "### " "/etc/cendrawasih/database/ssh/ssh.db" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
sed -i "/^### $user/d" /etc/cendrawasih/database/ssh/ssh.db
userdel $user >/dev/null 2>&1
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
echo " SSH/OVPN Account Deleted Successfully"
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
echo " Client Name : $user"
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"

echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
menu
